---
- name: Cleanup Disk Space
  hosts: prim
  become: yes
  tasks:
    - name: Find all log files
      ansible.builtin.find:
        paths: /var/log/nginx  # Ensure this path is correct
        recurse: yes
        patterns: "*.log"
      register: files_to_delete

    - name: Debug log files
      debug:
        var: files_to_delete.files

    - name: Delete all log files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
