---
- name: Cleanup Disk Space
  hosts: all
  become: yes
  tasks:
    - name: Find and delete old log files
      find:
        paths: /var/log/nginx
        age: 7d
        recurse: yes
        patterns: "*.log"
      register: error.log

    - name: Delete old log files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
