---
- name: Cleanup Disk Space
  hosts: all
  become: yes
  tasks:
    - name: Find all log files
      ansible.builtin.find:
        paths: /var/log/nginx  # Adjust path to your log directory
        recurse: yes
        patterns: "*.log"
      register: files_to_delete

    - name: Delete all log files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
