---
- name: Cleanup Disk Space
  hosts: prim
  tasks:
    - name: Find  old log files
      ansible.builtin.find:
        paths: /var/log/nginx
        patterns: "*.log"
      register: log_files

    - name: Delete old log files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ log_files.files }}"
